In [10]:
pwd


'C:\\Users\\student\\Desktop\\course of ewu\\Cse365 AKD\\cse 365 lab'

In [4]:
import pandas as pd
import numpy as mp


In [5]:
df = pd.read_csv("email.csv")

In [6]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5721  Subject: re : research and development charges...     0
5722  Subject: re : receipts from visit  jim ,  than...     0
5723  Subject: re : enron case study update  wow ! a...     0
5724  Subject: re : interest  david ,  please , call...     0
5725  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5726 rows x 2 columns]

In [7]:
df ['spam'].value_counts()

0    4358
1    1368
Name: spam, dtype: int64

In [9]:
df.drop_duplicates(inplace = True)

In [7]:
df ['spam'].value_counts()

0    4325
1    1368
Name: spam, dtype: int64

In [8]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5721  Subject: re : research and development charges...     0
5722  Subject: re : receipts from visit  jim ,  than...     0
5723  Subject: re : enron case study update  wow ! a...     0
5724  Subject: re : interest  david ,  please , call...     0
5725  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5693 rows x 2 columns]

In [9]:
df.isnull().sum()

text    0
spam    0
dtype: int64

# Seperate x & y

In [10]:
x= df.text.values

In [11]:
y= df.spam.values

#  split dataset

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
xtrain,xtest,ytrain,ytest =train_test_split(x,y,test_size=0.25)

# data processing

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
cv=CountVectorizer()
x_train =cv.fit_transform(xtrain)

In [16]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0]], dtype=int64)

# Naive Bayes Algorithm

In [17]:
from sklearn.naive_bayes import MultinomialNB

In [18]:
model = MultinomialNB()
model.fit(x_train, ytrain)

MultinomialNB()

In [19]:
x_test = cv.transform(xtest)

In [20]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
model.score(x_test,ytest)

0.9894662921348315

In [22]:
emails=['please help me doing my survey for thesis','you won a laptop for free pleaz fill up the survey to get it']

In [23]:
cv_emails =cv.transform(emails)

In [24]:
model.predict(cv_emails)

array([0, 1], dtype=int64)